<?php

namespace Database\Seeders;

use App\Models\Student;
use App\Models\StudentRemark;
use App\Models\User;
use Illuminate\Database\Seeder;

class StudentSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $admin = User::where('email', 'admin@uddan.com')->first();
        $priya = User::where('email', 'telecaller1@uddan.com')->first();
        $rahul = User::where('email', 'telecaller2@uddan.com')->first();
        $ananya = User::where('email', 'telecaller3@uddan.com')->first();

        $studentsData = [
            [
                'name' => 'Aarav Kumar',
                'father_name' => 'Ramesh Kumar',
                'dob' => '2004-05-15',
                'phone' => '9823412345',
                'whatsapp_no' => '9823412345',
                'qualification' => '12th Pass',
                'gender' => 'Male',
                'address' => 'Vill- Rampur, PO- Danapur, Patna',
                'city' => 'Patna',
                'course_interested' => 'B.Tech / Engineering Counseling',
                'source' => 'Counseling Form',
                'status' => 'Interested',
                'priority' => 'High',
                'assigned_to' => $priya?->id,
                'assigned_at' => now()->subDays(2),
                'assigned_by' => $admin?->id,
                'last_contacted_at' => now()->subHours(5),
                'next_followup_at' => now()->addDay()->setHour(14)->setMinute(0),
                'current_remarks' => 'Student wants counseling for CS branch under Bihar Student Credit Card scheme.',
                'remarks_history' => [
                    [
                        'user_id' => $priya?->id,
                        'call_outcome' => 'Connected',
                        'status' => 'Contacted',
                        'remarks' => 'Introductory counseling call. Explained available colleges and scholarship criteria.',
                        'created_at' => now()->subDays(1),
                        'next_followup_at' => now()->subHours(5),
                    ],
                    [
                        'user_id' => $priya?->id,
                        'call_outcome' => 'Interested',
                        'status' => 'Interested',
                        'remarks' => 'Student wants counseling for CS branch under Bihar Student Credit Card scheme.',
                        'created_at' => now()->subHours(5),
                        'next_followup_at' => now()->addDay()->setHour(14)->setMinute(0),
                    ],
                ]
            ],
            [
                'name' => 'Sneha Kumari',
                'father_name' => 'Sunil Singh',
                'dob' => '2003-11-20',
                'phone' => '9834567890',
                'whatsapp_no' => '9834567890',
                'qualification' => 'Graduation (Pursuing)',
                'gender' => 'Female',
                'address' => 'Ward No 4, Boring Road, Patna',
                'city' => 'Patna',
                'course_interested' => 'B.Sc Nursing & Paramedical',
                'source' => 'Website Form',
                'status' => 'Converted',
                'priority' => 'High',
                'assigned_to' => $priya?->id,
                'assigned_at' => now()->subDays(5),
                'assigned_by' => $admin?->id,
                'last_contacted_at' => now()->subDay(),
                'next_followup_at' => null,
                'current_remarks' => 'Counseling letter issued and admission token confirmed for Nursing College.',
                'remarks_history' => [
                    [
                        'user_id' => $priya?->id,
                        'call_outcome' => 'Connected',
                        'status' => 'Interested',
                        'remarks' => 'Father spoke on call. Inquired about hostel facility and college affiliation.',
                        'created_at' => now()->subDays(4),
                        'next_followup_at' => now()->subDays(2),
                    ],
                    [
                        'user_id' => $priya?->id,
                        'call_outcome' => 'Converted',
                        'status' => 'Converted',
                        'remarks' => 'Counseling letter issued and admission token confirmed for Nursing College.',
                        'created_at' => now()->subDay(),
                        'next_followup_at' => null,
                    ],
                ]
            ],
            [
                'name' => 'Vikram Sharma',
                'father_name' => 'Ajay Sharma',
                'dob' => '2005-01-10',
                'phone' => '9812398765',
                'whatsapp_no' => '9812398765',
                'qualification' => '10th Pass',
                'gender' => 'Male',
                'address' => 'Near Zero Mile, Muzaffarpur',
                'city' => 'Muzaffarpur',
                'course_interested' => 'Polytechnic Diploma',
                'source' => 'Counseling Form',
                'status' => 'Follow-up',
                'priority' => 'Medium',
                'assigned_to' => $rahul?->id,
                'assigned_at' => now()->subDays(3),
                'assigned_by' => $admin?->id,
                'last_contacted_at' => now()->subHours(3),
                'next_followup_at' => now()->addHours(4),
                'current_remarks' => 'Requested evening callback when father is home (6:30 PM).',
                'remarks_history' => [
                    [
                        'user_id' => $rahul?->id,
                        'call_outcome' => 'Callback Requested',
                        'status' => 'Follow-up',
                        'remarks' => 'Requested evening callback when father is home (6:30 PM).',
                        'created_at' => now()->subHours(3),
                        'next_followup_at' => now()->addHours(4),
                    ]
                ]
            ],
            [
                'name' => 'Pooja Kumari',
                'father_name' => 'Santosh Prasad',
                'dob' => '2004-08-25',
                'phone' => '9848012345',
                'whatsapp_no' => '9848012345',
                'qualification' => '12th Pass',
                'gender' => 'Female',
                'address' => 'Station Road, Gaya',
                'city' => 'Gaya',
                'course_interested' => 'BCA / Computer Applications',
                'source' => 'Counseling Form',
                'status' => 'Contacted',
                'priority' => 'High',
                'assigned_to' => $ananya?->id,
                'assigned_at' => now()->subDay(),
                'assigned_by' => $admin?->id,
                'last_contacted_at' => now()->subHours(2),
                'next_followup_at' => now()->addDay()->setHour(11)->setMinute(30),
                'current_remarks' => 'Connected. Wants counseling letter details sent on WhatsApp.',
                'remarks_history' => [
                    [
                        'user_id' => $ananya?->id,
                        'call_outcome' => 'Connected',
                        'status' => 'Contacted',
                        'remarks' => 'Connected. Wants counseling letter details sent on WhatsApp.',
                        'created_at' => now()->subHours(2),
                        'next_followup_at' => now()->addDay()->setHour(11)->setMinute(30),
                    ]
                ]
            ],
            [
                'name' => 'Manish Verma',
                'father_name' => 'Bipin Verma',
                'dob' => '2003-03-12',
                'phone' => '9890123456',
                'whatsapp_no' => '9890123456',
                'qualification' => '12th Pass',
                'gender' => 'Male',
                'address' => 'Bhagalpur City, Near Tower Chowk',
                'city' => 'Bhagalpur',
                'course_interested' => 'B.Pharma / Pharmacy',
                'source' => 'Bulk Upload',
                'status' => 'New',
                'priority' => 'Medium',
                'assigned_to' => null,
                'assigned_at' => null,
                'assigned_by' => null,
                'last_contacted_at' => null,
                'next_followup_at' => null,
                'current_remarks' => null,
                'remarks_history' => []
            ],
            [
                'name' => 'Anjali Raj',
                'father_name' => 'Rajendra Roy',
                'dob' => '2004-12-05',
                'phone' => '9447123456',
                'whatsapp_no' => '9447123456',
                'qualification' => '12th Pass',
                'gender' => 'Female',
                'address' => 'Darbhanga Bazar, Darbhanga',
                'city' => 'Darbhanga',
                'course_interested' => 'B.Tech / CS & AI',
                'source' => 'Website Form',
                'status' => 'New',
                'priority' => 'High',
                'assigned_to' => null,
                'assigned_at' => null,
                'assigned_by' => null,
                'last_contacted_at' => null,
                'next_followup_at' => null,
                'current_remarks' => null,
                'remarks_history' => []
            ],
            [
                'name' => 'Rohan Singh',
                'father_name' => 'Mahesh Singh',
                'dob' => '2004-02-18',
                'phone' => '9871123401',
                'whatsapp_no' => '9871123401',
                'qualification' => '12th Pass',
                'gender' => 'Male',
                'address' => 'Near Rajendra Stadium, Chapra',
                'city' => 'Chapra',
                'course_interested' => 'B.Tech / Mechanical',
                'source' => 'Website Form',
                'status' => 'Interested',
                'priority' => 'High',
                'assigned_to' => $priya?->id,
                'assigned_at' => now()->subDays(1),
                'assigned_by' => $admin?->id,
                'last_contacted_at' => now()->subHours(6),
                'next_followup_at' => now()->addDay()->setHour(10)->setMinute(30),
                'current_remarks' => 'Student wants DRCC Bihar Student Credit Card guidance for engineering.',
                'remarks_history' => [
                    [
                        'user_id' => $priya?->id,
                        'call_outcome' => 'Interested',
                        'status' => 'Interested',
                        'remarks' => 'Student wants DRCC Bihar Student Credit Card guidance for engineering.',
                        'created_at' => now()->subHours(6),
                        'next_followup_at' => now()->addDay()->setHour(10)->setMinute(30),
                    ]
                ]
            ],
            [
                'name' => 'Komal Sharma',
                'father_name' => 'Dinesh Sharma',
                'dob' => '2005-07-22',
                'phone' => '9871123402',
                'whatsapp_no' => '9871123402',
                'qualification' => '12th Pass',
                'gender' => 'Female',
                'address' => 'Main Road, Begusarai',
                'city' => 'Begusarai',
                'course_interested' => 'B.Sc Nursing',
                'source' => 'Counseling Form',
                'status' => 'Converted',
                'priority' => 'High',
                'assigned_to' => $priya?->id,
                'assigned_at' => now()->subDays(4),
                'assigned_by' => $admin?->id,
                'last_contacted_at' => now()->subHours(24),
                'next_followup_at' => null,
                'current_remarks' => 'Counseling completed. Admission letter issued under Bihar Student Credit Card.',
                'remarks_history' => [
                    [
                        'user_id' => $priya?->id,
                        'call_outcome' => 'Converted',
                        'status' => 'Converted',
                        'remarks' => 'Counseling completed. Admission letter issued under Bihar Student Credit Card.',
                        'created_at' => now()->subHours(24),
                        'next_followup_at' => null,
                    ]
                ]
            ],
            [
                'name' => 'Amit Kumar Yadav',
                'father_name' => 'Suresh Yadav',
                'dob' => '2003-09-14',
                'phone' => '9871123403',
                'whatsapp_no' => '9871123403',
                'qualification' => '12th Pass',
                'gender' => 'Male',
                'address' => 'Line Bazar, Purnia',
                'city' => 'Purnia',
                'course_interested' => 'B.Pharma',
                'source' => 'Bulk Upload',
                'status' => 'Follow-up',
                'priority' => 'Medium',
                'assigned_to' => $rahul?->id,
                'assigned_at' => now()->subDays(2),
                'assigned_by' => $admin?->id,
                'last_contacted_at' => now()->subHours(4),
                'next_followup_at' => now()->addHours(6),
                'current_remarks' => 'Parents will decide after discussing fee structure with local counselor.',
                'remarks_history' => [
                    [
                        'user_id' => $rahul?->id,
                        'call_outcome' => 'Callback Requested',
                        'status' => 'Follow-up',
                        'remarks' => 'Parents will decide after discussing fee structure with local counselor.',
                        'created_at' => now()->subHours(4),
                        'next_followup_at' => now()->addHours(6),
                    ]
                ]
            ],
            [
                'name' => 'Neha Gupta',
                'father_name' => 'Ravi Gupta',
                'dob' => '2004-03-30',
                'phone' => '9871123404',
                'whatsapp_no' => '9871123404',
                'qualification' => '12th Pass',
                'gender' => 'Female',
                'address' => 'Kankarbagh, Patna',
                'city' => 'Patna',
                'course_interested' => 'BCA',
                'source' => 'Website Form',
                'status' => 'Contacted',
                'priority' => 'High',
                'assigned_to' => $ananya?->id,
                'assigned_at' => now()->subDays(1),
                'assigned_by' => $admin?->id,
                'last_contacted_at' => now()->subHours(3),
                'next_followup_at' => now()->addDay()->setHour(12)->setMinute(0),
                'current_remarks' => 'Discussed curriculum and placement assistance. Follow up scheduled tomorrow.',
                'remarks_history' => [
                    [
                        'user_id' => $ananya?->id,
                        'call_outcome' => 'Connected',
                        'status' => 'Contacted',
                        'remarks' => 'Discussed curriculum and placement assistance. Follow up scheduled tomorrow.',
                        'created_at' => now()->subHours(3),
                        'next_followup_at' => now()->addDay()->setHour(12)->setMinute(0),
                    ]
                ]
            ],
            [
                'name' => 'Pankaj Mishra',
                'father_name' => 'Kishore Mishra',
                'dob' => '2004-10-10',
                'phone' => '9871123405',
                'whatsapp_no' => '9871123405',
                'qualification' => '10th Pass',
                'gender' => 'Male',
                'address' => 'Hajipur Station Road, Vaishali',
                'city' => 'Hajipur',
                'course_interested' => 'Polytechnic Diploma / Civil',
                'source' => 'Website Form',
                'status' => 'New',
                'priority' => 'Medium',
                'assigned_to' => null,
                'assigned_at' => null,
                'assigned_by' => null,
                'last_contacted_at' => null,
                'next_followup_at' => null,
                'current_remarks' => null,
                'remarks_history' => []
            ],
            [
                'name' => 'Ritu Choudhary',
                'father_name' => 'Gopal Choudhary',
                'dob' => '2005-04-12',
                'phone' => '9871123406',
                'whatsapp_no' => '9871123406',
                'qualification' => '12th Pass',
                'gender' => 'Female',
                'address' => 'Madhubani Town, Madhubani',
                'city' => 'Madhubani',
                'course_interested' => 'GNM / Nursing',
                'source' => 'Counseling Form',
                'status' => 'Interested',
                'priority' => 'High',
                'assigned_to' => $priya?->id,
                'assigned_at' => now()->subDays(2),
                'assigned_by' => $admin?->id,
                'last_contacted_at' => now()->subHours(8),
                'next_followup_at' => now()->addDays(2),
                'current_remarks' => 'Interested in government-approved nursing colleges with hostel facility.',
                'remarks_history' => [
                    [
                        'user_id' => $priya?->id,
                        'call_outcome' => 'Interested',
                        'status' => 'Interested',
                        'remarks' => 'Interested in government-approved nursing colleges with hostel facility.',
                        'created_at' => now()->subHours(8),
                        'next_followup_at' => now()->addDays(2),
                    ]
                ]
            ],
            [
                'name' => 'Deepak Ranjan',
                'father_name' => 'Manoj Ranjan',
                'dob' => '2003-12-01',
                'phone' => '9871123407',
                'whatsapp_no' => '9871123407',
                'qualification' => '12th Pass',
                'gender' => 'Male',
                'address' => 'Sasaram, Rohtas',
                'city' => 'Sasaram',
                'course_interested' => 'B.Tech / Electrical',
                'source' => 'Bulk Upload',
                'status' => 'New',
                'priority' => 'Low',
                'assigned_to' => null,
                'assigned_at' => null,
                'assigned_by' => null,
                'last_contacted_at' => null,
                'next_followup_at' => null,
                'current_remarks' => null,
                'remarks_history' => []
            ],
            [
                'name' => 'Shweta Bharti',
                'father_name' => 'Ramakant Bharti',
                'dob' => '2004-08-19',
                'phone' => '9871123408',
                'whatsapp_no' => '9871123408',
                'qualification' => 'Graduation (Pursuing)',
                'gender' => 'Female',
                'address' => 'Bihar Sharif, Nalanda',
                'city' => 'Nalanda',
                'course_interested' => 'B.Ed / Teacher Training',
                'source' => 'Website Form',
                'status' => 'Converted',
                'priority' => 'High',
                'assigned_to' => $rahul?->id,
                'assigned_at' => now()->subDays(5),
                'assigned_by' => $admin?->id,
                'last_contacted_at' => now()->subHours(12),
                'next_followup_at' => null,
                'current_remarks' => 'Counseling session completed. Admission finalized for B.Ed program.',
                'remarks_history' => [
                    [
                        'user_id' => $rahul?->id,
                        'call_outcome' => 'Converted',
                        'status' => 'Converted',
                        'remarks' => 'Counseling session completed. Admission finalized for B.Ed program.',
                        'created_at' => now()->subHours(12),
                        'next_followup_at' => null,
                    ]
                ]
            ],
            [
                'name' => 'Abhishek Pandey',
                'father_name' => 'Shailesh Pandey',
                'dob' => '2005-01-25',
                'phone' => '9871123409',
                'whatsapp_no' => '9871123409',
                'qualification' => '12th Pass',
                'gender' => 'Male',
                'address' => 'Arrah Court Road, Bhojpur',
                'city' => 'Arrah',
                'course_interested' => 'B.Sc Agriculture',
                'source' => 'Counseling Form',
                'status' => 'Follow-up',
                'priority' => 'Medium',
                'assigned_to' => $ananya?->id,
                'assigned_at' => now()->subDays(2),
                'assigned_by' => $admin?->id,
                'last_contacted_at' => now()->subHours(5),
                'next_followup_at' => now()->addDay()->setHour(15)->setMinute(0),
                'current_remarks' => 'Student requested college comparison brochure on WhatsApp.',
                'remarks_history' => [
                    [
                        'user_id' => $ananya?->id,
                        'call_outcome' => 'Callback Requested',
                        'status' => 'Follow-up',
                        'remarks' => 'Student requested college comparison brochure on WhatsApp.',
                        'created_at' => now()->subHours(5),
                        'next_followup_at' => now()->addDay()->setHour(15)->setMinute(0),
                    ]
                ]
            ],
            [
                'name' => 'Suman Kumari',
                'father_name' => 'Ashok Kumar',
                'dob' => '2004-06-17',
                'phone' => '9871123410',
                'whatsapp_no' => '9871123410',
                'qualification' => '12th Pass',
                'gender' => 'Female',
                'address' => 'Samastipur Bazar, Samastipur',
                'city' => 'Samastipur',
                'course_interested' => 'B.Pharma',
                'source' => 'Website Form',
                'status' => 'Contacted',
                'priority' => 'High',
                'assigned_to' => $priya?->id,
                'assigned_at' => now()->subDays(1),
                'assigned_by' => $admin?->id,
                'last_contacted_at' => now()->subHours(2),
                'next_followup_at' => now()->addDay()->setHour(16)->setMinute(0),
                'current_remarks' => 'Spoke with candidate. Sent list of PCI-approved colleges.',
                'remarks_history' => [
                    [
                        'user_id' => $priya?->id,
                        'call_outcome' => 'Connected',
                        'status' => 'Contacted',
                        'remarks' => 'Spoke with candidate. Sent list of PCI-approved colleges.',
                        'created_at' => now()->subHours(2),
                        'next_followup_at' => now()->addDay()->setHour(16)->setMinute(0),
                    ]
                ]
            ],
            [
                'name' => 'Vikash Kumar',
                'father_name' => 'Prabhat Kumar',
                'dob' => '2003-10-05',
                'phone' => '9871123411',
                'whatsapp_no' => '9871123411',
                'qualification' => '12th Pass',
                'gender' => 'Male',
                'address' => 'Katihar Junction Road, Katihar',
                'city' => 'Katihar',
                'course_interested' => 'BBA',
                'source' => 'Bulk Upload',
                'status' => 'New',
                'priority' => 'Medium',
                'assigned_to' => null,
                'assigned_at' => null,
                'assigned_by' => null,
                'last_contacted_at' => null,
                'next_followup_at' => null,
                'current_remarks' => null,
                'remarks_history' => []
            ],
            [
                'name' => 'Pallavi Sinha',
                'father_name' => 'Anil Sinha',
                'dob' => '2005-02-14',
                'phone' => '9871123412',
                'whatsapp_no' => '9871123412',
                'qualification' => '12th Pass',
                'gender' => 'Female',
                'address' => 'Anisabad, Patna',
                'city' => 'Patna',
                'course_interested' => 'B.Tech / CSE',
                'source' => 'Website Form',
                'status' => 'Interested',
                'priority' => 'High',
                'assigned_to' => $rahul?->id,
                'assigned_at' => now()->subDays(2),
                'assigned_by' => $admin?->id,
                'last_contacted_at' => now()->subHours(7),
                'next_followup_at' => now()->addDay()->setHour(11)->setMinute(0),
                'current_remarks' => 'Looking for top colleges with 100% placement track record.',
                'remarks_history' => [
                    [
                        'user_id' => $rahul?->id,
                        'call_outcome' => 'Interested',
                        'status' => 'Interested',
                        'remarks' => 'Looking for top colleges with 100% placement track record.',
                        'created_at' => now()->subHours(7),
                        'next_followup_at' => now()->addDay()->setHour(11)->setMinute(0),
                    ]
                ]
            ],
            [
                'name' => 'Gaurav Jha',
                'father_name' => 'Binod Jha',
                'dob' => '2004-11-28',
                'phone' => '9871123413',
                'whatsapp_no' => '9871123413',
                'qualification' => '10th Pass',
                'gender' => 'Male',
                'address' => 'Saharsa Bazar, Saharsa',
                'city' => 'Saharsa',
                'course_interested' => 'Polytechnic Diploma / Electrical',
                'source' => 'Counseling Form',
                'status' => 'New',
                'priority' => 'Low',
                'assigned_to' => null,
                'assigned_at' => null,
                'assigned_by' => null,
                'last_contacted_at' => null,
                'next_followup_at' => null,
                'current_remarks' => null,
                'remarks_history' => []
            ],
            [
                'name' => 'Kavita Kumari',
                'father_name' => 'Tribhuwan Prasad',
                'dob' => '2005-09-08',
                'phone' => '9871123414',
                'whatsapp_no' => '9871123414',
                'qualification' => '12th Pass',
                'gender' => 'Female',
                'address' => 'Motihari, East Champaran',
                'city' => 'Motihari',
                'course_interested' => 'B.Sc Nursing',
                'source' => 'Website Form',
                'status' => 'Interested',
                'priority' => 'High',
                'assigned_to' => $ananya?->id,
                'assigned_at' => now()->subDays(3),
                'assigned_by' => $admin?->id,
                'last_contacted_at' => now()->subHours(9),
                'next_followup_at' => now()->addDay()->setHour(14)->setMinute(30),
                'current_remarks' => 'Father ready for counseling registration. Verified Bihar Student Credit Card eligibility.',
                'remarks_history' => [
                    [
                        'user_id' => $ananya?->id,
                        'call_outcome' => 'Interested',
                        'status' => 'Interested',
                        'remarks' => 'Father ready for counseling registration. Verified Bihar Student Credit Card eligibility.',
                        'created_at' => now()->subHours(9),
                        'next_followup_at' => now()->addDay()->setHour(14)->setMinute(30),
                    ]
                ]
            ],
            [
                'name' => 'Md. Tariq Anwar',
                'father_name' => 'Md. Akhtar',
                'dob' => '2004-04-04',
                'phone' => '9871123415',
                'whatsapp_no' => '9871123415',
                'qualification' => '12th Pass',
                'gender' => 'Male',
                'address' => 'Siwan Main Road, Siwan',
                'city' => 'Siwan',
                'course_interested' => 'B.Tech / AI & Data Science',
                'source' => 'Website Form',
                'status' => 'Converted',
                'priority' => 'High',
                'assigned_to' => $priya?->id,
                'assigned_at' => now()->subDays(6),
                'assigned_by' => $admin?->id,
                'last_contacted_at' => now()->subDays(2),
                'next_followup_at' => null,
                'current_remarks' => 'Counseling session attended at Patna office. Allotted seat with full scholarship assistance.',
                'remarks_history' => [
                    [
                        'user_id' => $priya?->id,
                        'call_outcome' => 'Converted',
                        'status' => 'Converted',
                        'remarks' => 'Counseling session attended at Patna office. Allotted seat with full scholarship assistance.',
                        'created_at' => now()->subDays(2),
                        'next_followup_at' => null,
                    ]
                ]
            ],
            [
                'name' => 'Rani Patel',
                'father_name' => 'Jagdish Patel',
                'dob' => '2005-06-21',
                'phone' => '9871123416',
                'whatsapp_no' => '9871123416',
                'qualification' => '12th Pass',
                'gender' => 'Female',
                'address' => 'Buxar Town, Buxar',
                'city' => 'Buxar',
                'course_interested' => 'B.Pharma',
                'source' => 'Counseling Form',
                'status' => 'New',
                'priority' => 'Medium',
                'assigned_to' => null,
                'assigned_at' => null,
                'assigned_by' => null,
                'last_contacted_at' => null,
                'next_followup_at' => null,
                'current_remarks' => null,
                'remarks_history' => []
            ],
            [
                'name' => 'Saurav Banerjee',
                'father_name' => 'Subhash Banerjee',
                'dob' => '2003-08-11',
                'phone' => '9871123417',
                'whatsapp_no' => '9871123417',
                'qualification' => '12th Pass',
                'gender' => 'Male',
                'address' => 'Kadamkuan, Patna',
                'city' => 'Patna',
                'course_interested' => 'BCA / IT Management',
                'source' => 'Website Form',
                'status' => 'Follow-up',
                'priority' => 'High',
                'assigned_to' => $rahul?->id,
                'assigned_at' => now()->subDays(2),
                'assigned_by' => $admin?->id,
                'last_contacted_at' => now()->subHours(6),
                'next_followup_at' => now()->addDay()->setHour(17)->setMinute(0),
                'current_remarks' => 'Follow-up on credit card document verification list.',
                'remarks_history' => [
                    [
                        'user_id' => $rahul?->id,
                        'call_outcome' => 'Callback Requested',
                        'status' => 'Follow-up',
                        'remarks' => 'Follow-up on credit card document verification list.',
                        'created_at' => now()->subHours(6),
                        'next_followup_at' => now()->addDay()->setHour(17)->setMinute(0),
                    ]
                ]
            ],
            [
                'name' => 'Pooja Thakur',
                'father_name' => 'Naresh Thakur',
                'dob' => '2004-12-19',
                'phone' => '9871123418',
                'whatsapp_no' => '9871123418',
                'qualification' => '12th Pass',
                'gender' => 'Female',
                'address' => 'Jehanabad Bazar, Jehanabad',
                'city' => 'Jehanabad',
                'course_interested' => 'B.Sc Nursing',
                'source' => 'Bulk Upload',
                'status' => 'New',
                'priority' => 'Medium',
                'assigned_to' => null,
                'assigned_at' => null,
                'assigned_by' => null,
                'last_contacted_at' => null,
                'next_followup_at' => null,
                'current_remarks' => null,
                'remarks_history' => []
            ],
            [
                'name' => 'Rahul Kashyap',
                'father_name' => 'Santosh Kashyap',
                'dob' => '2004-01-15',
                'phone' => '9871123419',
                'whatsapp_no' => '9871123419',
                'qualification' => '12th Pass',
                'gender' => 'Male',
                'address' => 'Dehri On Sone, Rohtas',
                'city' => 'Dehri',
                'course_interested' => 'B.Tech / Mechanical',
                'source' => 'Website Form',
                'status' => 'Contacted',
                'priority' => 'Medium',
                'assigned_to' => $ananya?->id,
                'assigned_at' => now()->subDays(1),
                'assigned_by' => $admin?->id,
                'last_contacted_at' => now()->subHours(4),
                'next_followup_at' => now()->addDay()->setHour(13)->setMinute(0),
                'current_remarks' => 'Informed about counseling schedule and documents needed.',
                'remarks_history' => [
                    [
                        'user_id' => $ananya?->id,
                        'call_outcome' => 'Connected',
                        'status' => 'Contacted',
                        'remarks' => 'Informed about counseling schedule and documents needed.',
                        'created_at' => now()->subHours(4),
                        'next_followup_at' => now()->addDay()->setHour(13)->setMinute(0),
                    ]
                ]
            ],
        ];

        foreach ($studentsData as $data) {
            $remarksHistory = $data['remarks_history'] ?? [];
            unset($data['remarks_history']);

            $student = Student::create($data);

            foreach ($remarksHistory as $rem) {
                StudentRemark::create([
                    'student_id' => $student->id,
                    'user_id' => $rem['user_id'],
                    'call_outcome' => $rem['call_outcome'],
                    'status' => $rem['status'],
                    'remarks' => $rem['remarks'],
                    'next_followup_at' => $rem['next_followup_at'],
                    'created_at' => $rem['created_at'],
                ]);
            }
        }
    }
}
