@extends('frontend.layout')

@section('title', 'Available Courses — Udaan Foundation')

@section('content')
<section class="section section-light">
  <div class="container">
    <div class="section-title fade-in">
      <h2>Available Courses</h2>
      <p>Explore the complete list of undergraduate, diploma, professional, and management courses available for admission.</p>
    </div>

    <div class="info-card fade-in" style="margin-bottom:30px;">
      <div style="display:flex;align-items:center;justify-content:space-between;gap:16px;flex-wrap:wrap;">
        <div>
          <h3 style="margin-bottom:8px;"><i class="fas fa-graduation-cap"></i> Courses Under Counselling</h3>
          <p style="margin:0; color:#555;">Admissions are open across engineering, diploma, healthcare, nursing, law, business, media, agriculture, and hospitality programs.</p>
        </div>
        <a href="{{ route('frontend.apply') }}" class="btn btn-primary">Apply Now</a>
      </div>
    </div>

    <div class="info-card fade-in" style="padding:0; overflow:hidden; border-radius:14px;">
      <div style="background:linear-gradient(135deg,#014655,#026d7e); color:#fff; padding:18px 22px; font-weight:700; letter-spacing:0.03em;">
        Available Programs
      </div>
      <div style="overflow-x:auto;">
        <table style="width:100%; border-collapse:collapse; min-width:900px;">
          <thead>
            <tr style="background:#f8f9fa;">
              <th style="padding:14px 12px; text-align:left; border-bottom:1px solid #e9ecef;">Course Group</th>
              <th style="padding:14px 12px; text-align:left; border-bottom:1px solid #e9ecef;">Course Name</th>
              <th style="padding:14px 12px; text-align:left; border-bottom:1px solid #e9ecef;">Duration</th>
              <th style="padding:14px 12px; text-align:left; border-bottom:1px solid #e9ecef;">Eligibility</th>
              <th style="padding:14px 12px; text-align:left; border-bottom:1px solid #e9ecef;">Action</th>
            </tr>
          </thead>
          <tbody>
            <tr><td style="padding:14px 12px; border-bottom:1px solid #f0f0f0;">Engineering / Diploma</td><td style="padding:14px 12px; border-bottom:1px solid #f0f0f0;">Polytechnic</td><td style="padding:14px 12px; border-bottom:1px solid #f0f0f0;">3 Years</td><td style="padding:14px 12px; border-bottom:1px solid #f0f0f0;">10th Pass</td><td style="padding:14px 12px; border-bottom:1px solid #f0f0f0;"><a href="{{ route('frontend.apply') }}" class="btn-link">Apply <i class="fas fa-arrow-right"></i></a></td></tr>
            <tr><td style="padding:14px 12px; border-bottom:1px solid #f0f0f0;">Engineering / Diploma</td><td style="padding:14px 12px; border-bottom:1px solid #f0f0f0;">Polytechnic (Lateral Entry)</td><td style="padding:14px 12px; border-bottom:1px solid #f0f0f0;">2 Years</td><td style="padding:14px 12px; border-bottom:1px solid #f0f0f0;">12th Pass</td><td style="padding:14px 12px; border-bottom:1px solid #f0f0f0;"><a href="{{ route('frontend.apply') }}" class="btn-link">Apply <i class="fas fa-arrow-right"></i></a></td></tr>
            <tr><td style="padding:14px 12px; border-bottom:1px solid #f0f0f0;">Engineering</td><td style="padding:14px 12px; border-bottom:1px solid #f0f0f0;">B.Tech / B.E. (Any Branch)</td><td style="padding:14px 12px; border-bottom:1px solid #f0f0f0;">4 Years</td><td style="padding:14px 12px; border-bottom:1px solid #f0f0f0;">12th (PCM)</td><td style="padding:14px 12px; border-bottom:1px solid #f0f0f0;"><a href="{{ route('frontend.apply') }}" class="btn-link">Apply <i class="fas fa-arrow-right"></i></a></td></tr>
            <tr><td style="padding:14px 12px; border-bottom:1px solid #f0f0f0;">Engineering</td><td style="padding:14px 12px; border-bottom:1px solid #f0f0f0;">B.Tech Bio-tech</td><td style="padding:14px 12px; border-bottom:1px solid #f0f0f0;">4 Years</td><td style="padding:14px 12px; border-bottom:1px solid #f0f0f0;">12th (PCB)</td><td style="padding:14px 12px; border-bottom:1px solid #f0f0f0;"><a href="{{ route('frontend.apply') }}" class="btn-link">Apply <i class="fas fa-arrow-right"></i></a></td></tr>
            <tr><td style="padding:14px 12px; border-bottom:1px solid #f0f0f0;">Pharmacy</td><td style="padding:14px 12px; border-bottom:1px solid #f0f0f0;">D.Pharma</td><td style="padding:14px 12px; border-bottom:1px solid #f0f0f0;">2 Years</td><td style="padding:14px 12px; border-bottom:1px solid #f0f0f0;">12th (PCM/PCB)</td><td style="padding:14px 12px; border-bottom:1px solid #f0f0f0;"><a href="{{ route('frontend.apply') }}" class="btn-link">Apply <i class="fas fa-arrow-right"></i></a></td></tr>
            <tr><td style="padding:14px 12px; border-bottom:1px solid #f0f0f0;">Pharmacy</td><td style="padding:14px 12px; border-bottom:1px solid #f0f0f0;">B.Pharma</td><td style="padding:14px 12px; border-bottom:1px solid #f0f0f0;">4 Years</td><td style="padding:14px 12px; border-bottom:1px solid #f0f0f0;">12th (PCM/PCB)</td><td style="padding:14px 12px; border-bottom:1px solid #f0f0f0;"><a href="{{ route('frontend.apply') }}" class="btn-link">Apply <i class="fas fa-arrow-right"></i></a></td></tr>
            <tr><td style="padding:14px 12px; border-bottom:1px solid #f0f0f0;">Paramedical</td><td style="padding:14px 12px; border-bottom:1px solid #f0f0f0;">BPT (Bachelor in Physiotherapy)</td><td style="padding:14px 12px; border-bottom:1px solid #f0f0f0;">3 Years</td><td style="padding:14px 12px; border-bottom:1px solid #f0f0f0;">12th (PCB)</td><td style="padding:14px 12px; border-bottom:1px solid #f0f0f0;"><a href="{{ route('frontend.apply') }}" class="btn-link">Apply <i class="fas fa-arrow-right"></i></a></td></tr>
            <tr><td style="padding:14px 12px; border-bottom:1px solid #f0f0f0;">Paramedical</td><td style="padding:14px 12px; border-bottom:1px solid #f0f0f0;">BMLT</td><td style="padding:14px 12px; border-bottom:1px solid #f0f0f0;">3 Years</td><td style="padding:14px 12px; border-bottom:1px solid #f0f0f0;">12th (PCB)</td><td style="padding:14px 12px; border-bottom:1px solid #f0f0f0;"><a href="{{ route('frontend.apply') }}" class="btn-link">Apply <i class="fas fa-arrow-right"></i></a></td></tr>
            <tr><td style="padding:14px 12px; border-bottom:1px solid #f0f0f0;">Paramedical</td><td style="padding:14px 12px; border-bottom:1px solid #f0f0f0;">BOT</td><td style="padding:14px 12px; border-bottom:1px solid #f0f0f0;">3 Years</td><td style="padding:14px 12px; border-bottom:1px solid #f0f0f0;">12th (PCB)</td><td style="padding:14px 12px; border-bottom:1px solid #f0f0f0;"><a href="{{ route('frontend.apply') }}" class="btn-link">Apply <i class="fas fa-arrow-right"></i></a></td></tr>
            <tr><td style="padding:14px 12px; border-bottom:1px solid #f0f0f0;">Paramedical</td><td style="padding:14px 12px; border-bottom:1px solid #f0f0f0;">Optometry</td><td style="padding:14px 12px; border-bottom:1px solid #f0f0f0;">3 Years</td><td style="padding:14px 12px; border-bottom:1px solid #f0f0f0;">12th (PCB)</td><td style="padding:14px 12px; border-bottom:1px solid #f0f0f0;"><a href="{{ route('frontend.apply') }}" class="btn-link">Apply <i class="fas fa-arrow-right"></i></a></td></tr>
            <tr><td style="padding:14px 12px; border-bottom:1px solid #f0f0f0;">Paramedical</td><td style="padding:14px 12px; border-bottom:1px solid #f0f0f0;">DMLT</td><td style="padding:14px 12px; border-bottom:1px solid #f0f0f0;">2 Years</td><td style="padding:14px 12px; border-bottom:1px solid #f0f0f0;">12th (PCB)</td><td style="padding:14px 12px; border-bottom:1px solid #f0f0f0;"><a href="{{ route('frontend.apply') }}" class="btn-link">Apply <i class="fas fa-arrow-right"></i></a></td></tr>
            <tr><td style="padding:14px 12px; border-bottom:1px solid #f0f0f0;">Paramedical</td><td style="padding:14px 12px; border-bottom:1px solid #f0f0f0;">Radiology</td><td style="padding:14px 12px; border-bottom:1px solid #f0f0f0;">2 Years</td><td style="padding:14px 12px; border-bottom:1px solid #f0f0f0;">12th (PCB)</td><td style="padding:14px 12px; border-bottom:1px solid #f0f0f0;"><a href="{{ route('frontend.apply') }}" class="btn-link">Apply <i class="fas fa-arrow-right"></i></a></td></tr>
            <tr><td style="padding:14px 12px; border-bottom:1px solid #f0f0f0;">Paramedical</td><td style="padding:14px 12px; border-bottom:1px solid #f0f0f0;">O.T Technician</td><td style="padding:14px 12px; border-bottom:1px solid #f0f0f0;">2 Years</td><td style="padding:14px 12px; border-bottom:1px solid #f0f0f0;">12th (PCB)</td><td style="padding:14px 12px; border-bottom:1px solid #f0f0f0;"><a href="{{ route('frontend.apply') }}" class="btn-link">Apply <i class="fas fa-arrow-right"></i></a></td></tr>
            <tr><td style="padding:14px 12px; border-bottom:1px solid #f0f0f0;">Paramedical</td><td style="padding:14px 12px; border-bottom:1px solid #f0f0f0;">X-Ray Technician</td><td style="padding:14px 12px; border-bottom:1px solid #f0f0f0;">2 Years</td><td style="padding:14px 12px; border-bottom:1px solid #f0f0f0;">12th (PCB)</td><td style="padding:14px 12px; border-bottom:1px solid #f0f0f0;"><a href="{{ route('frontend.apply') }}" class="btn-link">Apply <i class="fas fa-arrow-right"></i></a></td></tr>
            <tr><td style="padding:14px 12px; border-bottom:1px solid #f0f0f0;">Paramedical</td><td style="padding:14px 12px; border-bottom:1px solid #f0f0f0;">Dialysis Technology</td><td style="padding:14px 12px; border-bottom:1px solid #f0f0f0;">2 Years</td><td style="padding:14px 12px; border-bottom:1px solid #f0f0f0;">12th (PCB)</td><td style="padding:14px 12px; border-bottom:1px solid #f0f0f0;"><a href="{{ route('frontend.apply') }}" class="btn-link">Apply <i class="fas fa-arrow-right"></i></a></td></tr>
            <tr><td style="padding:14px 12px; border-bottom:1px solid #f0f0f0;">Nursing</td><td style="padding:14px 12px; border-bottom:1px solid #f0f0f0;">GNM</td><td style="padding:14px 12px; border-bottom:1px solid #f0f0f0;">3 Years</td><td style="padding:14px 12px; border-bottom:1px solid #f0f0f0;">12th (PCB)</td><td style="padding:14px 12px; border-bottom:1px solid #f0f0f0;"><a href="{{ route('frontend.apply') }}" class="btn-link">Apply <i class="fas fa-arrow-right"></i></a></td></tr>
            <tr><td style="padding:14px 12px; border-bottom:1px solid #f0f0f0;">Nursing</td><td style="padding:14px 12px; border-bottom:1px solid #f0f0f0;">B.Sc Nursing</td><td style="padding:14px 12px; border-bottom:1px solid #f0f0f0;">4 Years</td><td style="padding:14px 12px; border-bottom:1px solid #f0f0f0;">12th (PCB)</td><td style="padding:14px 12px; border-bottom:1px solid #f0f0f0;"><a href="{{ route('frontend.apply') }}" class="btn-link">Apply <i class="fas fa-arrow-right"></i></a></td></tr>
            <tr><td style="padding:14px 12px; border-bottom:1px solid #f0f0f0;">Agriculture</td><td style="padding:14px 12px; border-bottom:1px solid #f0f0f0;">B.Sc Agriculture</td><td style="padding:14px 12px; border-bottom:1px solid #f0f0f0;">4 Years</td><td style="padding:14px 12px; border-bottom:1px solid #f0f0f0;">12th (PCM/PCB)</td><td style="padding:14px 12px; border-bottom:1px solid #f0f0f0;"><a href="{{ route('frontend.apply') }}" class="btn-link">Apply <i class="fas fa-arrow-right"></i></a></td></tr>
            <tr><td style="padding:14px 12px; border-bottom:1px solid #f0f0f0;">Law</td><td style="padding:14px 12px; border-bottom:1px solid #f0f0f0;">BA-LLB / B.Com LLB</td><td style="padding:14px 12px; border-bottom:1px solid #f0f0f0;">5 Years</td><td style="padding:14px 12px; border-bottom:1px solid #f0f0f0;">12th Pass</td><td style="padding:14px 12px; border-bottom:1px solid #f0f0f0;"><a href="{{ route('frontend.apply') }}" class="btn-link">Apply <i class="fas fa-arrow-right"></i></a></td></tr>
            <tr><td style="padding:14px 12px; border-bottom:1px solid #f0f0f0;">Law</td><td style="padding:14px 12px; border-bottom:1px solid #f0f0f0;">BBA-LLB</td><td style="padding:14px 12px; border-bottom:1px solid #f0f0f0;">5 Years</td><td style="padding:14px 12px; border-bottom:1px solid #f0f0f0;">12th Pass</td><td style="padding:14px 12px; border-bottom:1px solid #f0f0f0;"><a href="{{ route('frontend.apply') }}" class="btn-link">Apply <i class="fas fa-arrow-right"></i></a></td></tr>
            <tr><td style="padding:14px 12px; border-bottom:1px solid #f0f0f0;">Management</td><td style="padding:14px 12px; border-bottom:1px solid #f0f0f0;">BBA</td><td style="padding:14px 12px; border-bottom:1px solid #f0f0f0;">3 Years</td><td style="padding:14px 12px; border-bottom:1px solid #f0f0f0;">12th Pass</td><td style="padding:14px 12px; border-bottom:1px solid #f0f0f0;"><a href="{{ route('frontend.apply') }}" class="btn-link">Apply <i class="fas fa-arrow-right"></i></a></td></tr>
            <tr><td style="padding:14px 12px; border-bottom:1px solid #f0f0f0;">Management</td><td style="padding:14px 12px; border-bottom:1px solid #f0f0f0;">MBA</td><td style="padding:14px 12px; border-bottom:1px solid #f0f0f0;">2 Years</td><td style="padding:14px 12px; border-bottom:1px solid #f0f0f0;">Graduation</td><td style="padding:14px 12px; border-bottom:1px solid #f0f0f0;"><a href="{{ route('frontend.apply') }}" class="btn-link">Apply <i class="fas fa-arrow-right"></i></a></td></tr>
            <tr><td style="padding:14px 12px; border-bottom:1px solid #f0f0f0;">Media</td><td style="padding:14px 12px; border-bottom:1px solid #f0f0f0;">BJMC</td><td style="padding:14px 12px; border-bottom:1px solid #f0f0f0;">3 Years</td><td style="padding:14px 12px; border-bottom:1px solid #f0f0f0;">12th Pass</td><td style="padding:14px 12px; border-bottom:1px solid #f0f0f0;"><a href="{{ route('frontend.apply') }}" class="btn-link">Apply <i class="fas fa-arrow-right"></i></a></td></tr>
            <tr><td style="padding:14px 12px; border-bottom:1px solid #f0f0f0;">Computer Applications</td><td style="padding:14px 12px; border-bottom:1px solid #f0f0f0;">BCA</td><td style="padding:14px 12px; border-bottom:1px solid #f0f0f0;">3 Years</td><td style="padding:14px 12px; border-bottom:1px solid #f0f0f0;">12th Pass</td><td style="padding:14px 12px; border-bottom:1px solid #f0f0f0;"><a href="{{ route('frontend.apply') }}" class="btn-link">Apply <i class="fas fa-arrow-right"></i></a></td></tr>
            <tr><td style="padding:14px 12px; border-bottom:1px solid #f0f0f0;">Computer Applications</td><td style="padding:14px 12px; border-bottom:1px solid #f0f0f0;">MCA</td><td style="padding:14px 12px; border-bottom:1px solid #f0f0f0;">2 Years</td><td style="padding:14px 12px; border-bottom:1px solid #f0f0f0;">Graduation</td><td style="padding:14px 12px; border-bottom:1px solid #f0f0f0;"><a href="{{ route('frontend.apply') }}" class="btn-link">Apply <i class="fas fa-arrow-right"></i></a></td></tr>
            <tr><td style="padding:14px 12px; border-bottom:1px solid #f0f0f0;">Hospitality</td><td style="padding:14px 12px; border-bottom:1px solid #f0f0f0;">BHM</td><td style="padding:14px 12px; border-bottom:1px solid #f0f0f0;">4 Years</td><td style="padding:14px 12px; border-bottom:1px solid #f0f0f0;">12th Pass</td><td style="padding:14px 12px; border-bottom:1px solid #f0f0f0;"><a href="{{ route('frontend.apply') }}" class="btn-link">Apply <i class="fas fa-arrow-right"></i></a></td></tr>
            <tr><td style="padding:14px 12px; border-bottom:1px solid #f0f0f0;">Hospitality</td><td style="padding:14px 12px; border-bottom:1px solid #f0f0f0;">Bachelor in Hospital Management</td><td style="padding:14px 12px; border-bottom:1px solid #f0f0f0;">3 Years</td><td style="padding:14px 12px; border-bottom:1px solid #f0f0f0;">12th Pass</td><td style="padding:14px 12px; border-bottom:1px solid #f0f0f0;"><a href="{{ route('frontend.apply') }}" class="btn-link">Apply <i class="fas fa-arrow-right"></i></a></td></tr>
          </tbody>
        </table>
      </div>
    </div>

    <div class="info-card fade-in" style="margin-top:30px;">
      <h3><i class="fas fa-info-circle"></i> Important Notes</h3>
      <ul>
        <li><i class="fas fa-check-circle"></i> Eligibility and intake may vary by institution and course.</li>
        <li><i class="fas fa-check-circle"></i> Students are advised to verify the latest admission criteria before applying.</li>
        <li><i class="fas fa-check-circle"></i> Counselling and document support are available for all listed programs.</li>
      </ul>
    </div>
  </div>
</section>
@endsection
